### ISSUE TITLE
[tabs] Check for chrome.lastError and reject a promise if found

### ISSUE THREAD

**Issue by bausano** [exteranto/framework#109]
**Describe the bug**
Tab methods for chrome do not check for `lastError`, which results in not rejected promises and console pollution.

**To reproduce**
Steps to reproduce the behaviour:
1. Go to background page console
2. Try to `Tabs.get` a nonexisting tab
4. See error being printed in the console

**Expected behaviour**
Promise to be rejected and `lastError` to be caught.

**Comment by kouks** [comment]
Closed by #111
