### ISSUE TITLE
[global] Define all exceptions thrown in the application in the @exteranto/exceptions package

### ISSUE THREAD

**Issue by kouks** [exteranto/framework#12]
This way all exceptions will have a name and users will be able to listen for those exceptions in their router.

**Comment by bausano** [comment]
This is linked to #6 right?

**Comment by bausano** [comment]
@kouks I believe this is done?

**Comment by kouks** [comment]
@bausano Missing some in tabs still?

**Comment by kouks** [comment]
Irrelevant since we are getting rid of this package for 3.0.0.
