### ISSUE TITLE
[cookies] Cover cookies APIs.

### ISSUE THREAD

**Issue by bausano** [exteranto/framework#19]

**Comment by bausano** [comment]
There is no Safari API that I know of that could simulate this behavior. Reading cookies from the content script and sending them to the background page sounds like a hassle plus would not work the same way as you could only read cookies from pages that are currently open.

Hence I suggest we either make use of Unimplementable exception or, which I prefer, we simply don't bind Cookies service for `Browser.SAFARI` and mention it in the documentation that it is preferred to combine calls to this service with a compatibility service.

**Comment by kouks** [comment]
closed by #21
