### ISSUE TITLE
[management] Badge click event

### ISSUE THREAD

**Issue by kouks** [exteranto/framework#34]
Add event listener for badge click, solve for safari.

**Comment by bausano** [comment]
closed by #38 

This implies that Exteranto completely deprecated overlay popup. The only way to display UI to the user now in injected HTML to content script.

This design decision was based on our experience with popups in a browser. The default one is hard to develop UI for and is overall inconsistent. Also, it closes on click outside of the popup, which often is not desired.

**Comment by bausano** [comment]
More backing for this design decision comes from Grammarly [dev blog](https://tech.grammarly.com/blog/building-browser-extensions-at-scale#how-to-set-up-a-popup):

> If your extension has a toolbar button, it will probably have a popup that opens on a button click. By default, you can add an HTML page popup.html (Chrome, Firefox, Safari). This approach has pitfalls. You will have to deal with differences in the way browsers open it. In some cases, the popup appears with animation. In some cases, it will jump because of a height change after your UI renders on the client side. You can spend hours fixing that.
Another approach is to handle the toolbar button click and inject your popup UI to the page. In this case, you will have full control over the popup interface. This is how Pocket extension does it.
