### ISSUE TITLE
[api] Safari browser action @Listen registered on Chrome

### ISSUE THREAD

**Issue by kouks** [exteranto/framework#56]
**Describe the bug**
Safari `BrowserAction` has a `@Listen` annotation on one of its methods and it is registered even in chrome.

**To Reproduce**
1. Load unpacked skeleton with browser action provider loaded
2. Got to any open tab
4. See error in the background script console

**Expected behavior**
The listener should not be registered.

**Comment by bausano** [comment]
closed by #57
