### ISSUE TITLE
[events] Events should be fireable based on inheritance tree

### ISSUE THREAD

**Issue by bausano** [exteranto/framework#73]
If events are fired based on inheritance, we could delete lots of redundant config codes.

The desired behavior is something like this:

```
class A extends Event

class B extends A

.touch(A).addListener(listener)

.fire(new B)

// listener is fired with event B
```

Pseudo code:
`fireable (e /*: Event*/) { eachType(T => T.isPrototypeOf(e.constructor) || e.constructor === T) } `

**Comment by kouks** [comment]
closed by #74
