### ISSUE TITLE
[messaging] custom exception when receiving end does not exist

### ISSUE THREAD

**Issue by kouks** [exteranto/framework#99]
**Describe the bug**
Error is thrown when trying to establish a connection with a content script that is not loaded.

**To reproduce**
Steps to reproduce the behaviour:
1. Go to google chrome new tab
2. Try to establish a connection with the content script
3. See error in the console

**Expected behaviour**
The action should throw a custom error defined in the exteranto package.

**Comment by bausano** [comment]
closed by #115
